name: Tag New Version

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      # Checke das Repository aus
      - name: Checkout repository
        uses: actions/checkout@v2

      # Erstelle ein neues Versionstag basierend auf der aktuellen Version in der Plugin-Datei
      - name: Generate new version tag
        id: tag
        run: |
          # Lies die Version aus der Plugin-Datei (z. B. aus der header.php oder plugin.php)
          VERSION=$(grep -oP 'Version:\s*\K[^\s]+' athena-ai.php)
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      # Erstelle und pushe das neue Tag
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "v${{ steps.tag.outputs.version }}" -m "Release version ${{ steps.tag.outputs.version }}"
          git push origin "v${{ steps.tag.outputs.version }}"
