name: Create Release Tag

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "info@dz-ecom.de"
          git config --global user.name "dz-ecommerce"
          git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean up tags
        run: |
          echo "Cleaning up tags..."
          git tag -l | xargs -n 1 git tag -d
          git fetch --tags --prune-tags

      - name: Get current version
        id: get_version
        run: |
          echo "Reading version from athena-ai.php..."
          cat athena-ai/athena-ai.php | grep "Version:"
          VERSION=$(grep "Version:" athena-ai/athena-ai.php | sed -n 's/.*Version: *\([0-9.]*\).*/\1/p')
          echo "Extracted version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          GIT_AUTHOR_NAME: dz-ecommerce
          GIT_AUTHOR_EMAIL: info@dz-ecom.de
          GIT_COMMITTER_NAME: dz-ecommerce
          GIT_COMMITTER_EMAIL: info@dz-ecom.de
        run: |
          echo "Creating tag v${{ steps.get_version.outputs.version }}..."
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release version ${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
