name: Automated Release

env:
  PRERELEASE: "false"

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pull-requests: write

# Cancel in-progress jobs or runs for the current workflow run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "info@dz-ecom.de"
          git config --global user.name "dz-ecommerce"
          git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: |
          echo "Reading version from athena-ai.php..."
          cat athena-ai/athena-ai.php | grep "Version:"
          VERSION=$(grep "Version:" athena-ai/athena-ai.php | sed -n 's/.*Version: *\([0-9.]*\).*/\1/p')
          echo "Extracted version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release for v${{ steps.get_version.outputs.version }}

            Changes in this release:
            - Initial release
          prerelease: ${{ env.PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
