name: Create Release Tag

on:
  push:
    branches: [main]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          git config --global user.email "info@dz-ecom.de"
          git config --global user.name "dz-ecommerce"
          git tag -a v1.0.0 -m "Release version 1.0.0"
          git push origin v1.0.0
