name: Create Release Tag

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "info@dz-ecom.de"
          git config --global user.name "dz-ecommerce"
          git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep "Version:" athena-ai/athena-ai.php | cut -d' ' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l | grep -q "^v${{ steps.get_version.outputs.version }}$"; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        env:
          GIT_AUTHOR_NAME: dz-ecommerce
          GIT_AUTHOR_EMAIL: info@dz-ecom.de
          GIT_COMMITTER_NAME: dz-ecommerce
          GIT_COMMITTER_EMAIL: info@dz-ecom.de
        run: |
          git tag -a "v${{ steps.get_version.outputs.version }}" -m "Release version ${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
